sonar.projectKey=mi-laravel-app
sonar.projectName=Mi App Laravel
sonar.language=php
sonar.sources=app,resources,routes
sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.password=juansara1395 